<?php
namespace VGBM\PM\Roles;

use VGBM\PM\PostTypes\PostTypes;

if (!defined('ABSPATH')) { exit; }

final class Roles {

    public const CAP_MANAGE = 'vgbm_manage';

    public function register(): void {
        // CPTs are registered on init; admin_init happens after init in wp-admin.
        add_action('admin_init', [$this, 'register_roles_and_caps']);
    }

    private function ensure_role(string $role_key, string $label, array $base_caps = []): void {
        if (!get_role($role_key)) {
            add_role($role_key, $label, $base_caps);
        }
    }

    /**
     * Grants the full set of primitive capabilities generated by WordPress for a CPT.
     * This fixes cases where the header checkbox shows, but per-row checkboxes / row actions are missing.
     */
    private function add_all_caps_for_post_type(\WP_Role $role, string $post_type): void {
        $obj = get_post_type_object($post_type);
        if (!$obj || empty($obj->cap)) { return; }

        foreach ((array) $obj->cap as $cap) {
            if (is_string($cap) && $cap !== '') {
                $role->add_cap($cap);
            }
        }
    }

    public function register_roles_and_caps(): void {
        // Ensure roles exist.
        $this->ensure_role('vgbm_manager', __('VGBM Manager', 'vgbm-property-manager'), [
            self::CAP_MANAGE => true,
            'read' => true,
        ]);

        $this->ensure_role('vgbm_maintenance', __('VGBM Maintenance', 'vgbm-property-manager'), [
            self::CAP_MANAGE => true,
            'read' => true,
        ]);

        $this->ensure_role('vgbm_renter', __('VGBM Renter', 'vgbm-property-manager'), [
            'read' => true,
        ]);

        // VGBM Manager: full access to all VGBM CPTs.
        $manager = get_role('vgbm_manager');
        if ($manager) {
            $manager->add_cap(self::CAP_MANAGE);
            $manager->add_cap('read');

            $this->add_all_caps_for_post_type($manager, PostTypes::CPT_PORTFOLIO);
            $this->add_all_caps_for_post_type($manager, PostTypes::CPT_PROPERTY);
            $this->add_all_caps_for_post_type($manager, PostTypes::CPT_UNIT);
            $this->add_all_caps_for_post_type($manager, PostTypes::CPT_RENTER);
            $this->add_all_caps_for_post_type($manager, PostTypes::CPT_UTILITY);
            $this->add_all_caps_for_post_type($manager, PostTypes::CPT_READING);
            $this->add_all_caps_for_post_type($manager, PostTypes::CPT_ALLOCATION);
            $this->add_all_caps_for_post_type($manager, PostTypes::CPT_DOCUMENT);
            $this->add_all_caps_for_post_type($manager, PostTypes::CPT_CONTRACT);
            $this->add_all_caps_for_post_type($manager, PostTypes::CPT_TICKET);
        }

        // Maintenance: tickets only.
        $maint = get_role('vgbm_maintenance');
        if ($maint) {
            $maint->add_cap(self::CAP_MANAGE);
            $maint->add_cap('read');

            $this->add_all_caps_for_post_type($maint, PostTypes::CPT_TICKET);

            // Safety: do not edit/delete other users' tickets by default.
            $maint->remove_cap('edit_others_vgbm_tickets');
            $maint->remove_cap('delete_others_vgbm_tickets');
        }

        // Administrators: super users → full access.
        $admin = get_role('administrator');
        if ($admin) {
            $admin->add_cap(self::CAP_MANAGE);

            $this->add_all_caps_for_post_type($admin, PostTypes::CPT_PORTFOLIO);
            $this->add_all_caps_for_post_type($admin, PostTypes::CPT_PROPERTY);
            $this->add_all_caps_for_post_type($admin, PostTypes::CPT_UNIT);
            $this->add_all_caps_for_post_type($admin, PostTypes::CPT_RENTER);
            $this->add_all_caps_for_post_type($admin, PostTypes::CPT_UTILITY);
            $this->add_all_caps_for_post_type($admin, PostTypes::CPT_READING);
            $this->add_all_caps_for_post_type($admin, PostTypes::CPT_ALLOCATION);
            $this->add_all_caps_for_post_type($admin, PostTypes::CPT_DOCUMENT);
            $this->add_all_caps_for_post_type($admin, PostTypes::CPT_CONTRACT);
            $this->add_all_caps_for_post_type($admin, PostTypes::CPT_TICKET);
        }
    }
}
